version: '3.8'

services:
  pollyglot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-anthropic/claude-3.5-sonnet}
      - PUBLIC_APP_URL=${PUBLIC_APP_URL:-http://localhost:8000}
      - RATE_LIMIT_PER_MIN=${RATE_LIMIT_PER_MIN:-10}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=${DEBUG:-false}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - pollyglot-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - pollyglot-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pollyglot
    restart: unless-stopped
    networks:
      - pollyglot-network
    profiles:
      - with-proxy

volumes:
  redis_data:

networks:
  pollyglot-network:
    driver: bridge